//===========================================================================
//! 「自律人形（オートマタ）」のように単一の単語はそのまま置き換える形がいいかと思います。
//! 「自律人形」のように複数回使用されている単語の場合は先頭に@をつけるなどして単一の単語として対応してください。
//===========================================================================


#define		七竈町（ななかまどちょう）		ruby("ななかまどちょう") 七竈町 ruby
#define		速川麦（ティアーズブラッド）	ruby("ティアーズブラッド") 速川麦 ruby
#define		草浪（くさなみ）				ruby("くさなみ") 草浪 ruby
#define		兄（にい）						ruby("にい") 兄 ruby
#define		鳥（ちょう）					ruby("ちょう") 鳥 ruby
#define		稔（みの）						ruby("みの") 稔 ruby
#define		額（ひたい）					ruby("ひたい") 額 ruby
#define		初心（ウブ）					ruby("ウブ") 初心 ruby
#define		極限感覚（トリガー）			ruby("トリガー") 極限感覚 ruby
#define		嶽（クル）						ruby("クル") 嶽 ruby
#define		大人（アダルト）				ruby("アダルト") 大人 ruby
#define		時間（タイム）					ruby("タイム") 時間 ruby
#define		跋扈（ばっこ）					ruby("ばっこ") 跋扈 ruby
#define		古民ロケ（ルビ："KOMIN-ROKE"）	ruby("KOMIN-ROKE") 古民ロケ ruby
#define		愛羅（てぃあら）				ruby("てぃあら") 愛羅 ruby
#define		血痕（ケチャップ）				ruby("ケチャップ") 血痕 ruby
#define		御平町（ルビ：みだいらちょう）	ruby("みだいらちょう") 御平町 ruby
#define		褒賞（ルビ：ほうしょう）		ruby("ほうしょう") 褒賞 ruby
#define		枝垂（しだ）					ruby("しだ") 枝垂 ruby
#define		山笛町（ルビ：やまぶえちょう）	ruby("やまぶえちょう") 山笛町 ruby
#define		筑知市（ルビ：ちくしるし）		ruby("ちくしるし") 筑知市 ruby
#define		生存術（サバイバル）			ruby("サバイバル") 生存術 ruby
#define		貌（かお）						ruby("かお") 貌 ruby
// todo／絵文字実装							麦君（ハート）
#define		守屋絵美（ルビ：もりやえみ）	ruby("もりやえみ") 守屋絵美 ruby
#define		陽菜（ひな）					ruby("ひな") 陽菜 ruby
#define		理想郷（シャングリラ）			ruby("シャングリラ") 理想郷 ruby
#define		理想郷（ユートピア）			ruby("ユートピア") 理想郷 ruby
#define		理想郷（アヴァロン）			ruby("アヴァロン") 理想郷 ruby
#define		総羽愛乃（ふさばあいの）		ruby("ふさばあいの") 総羽愛乃 ruby
#define		運命（サダメ）					ruby("サダメ") 運命 ruby
#define		呼吸（おと）					ruby("おと") 呼吸 ruby
#define		葛餡（くずあん）				ruby("くずあん") 葛餡 ruby
#define		中庸（ちゅうよう）				ruby("ちゅうよう") 中庸 ruby
#define		地球（ほし）					ruby("ほし") 地球 ruby

//スピカ
#define		風音（かざおと）				ruby("かざおと") 風音 ruby
#define		菌輪（きんりん）				ruby("きんりん") 菌輪 ruby
#define		楔（くさび）					ruby("くさび") 楔 ruby
#define		漏斗雲（ろうとくも）			ruby("ろうとくも") 漏斗雲 ruby
#define		邪（よこしま）					ruby("よこしま") 邪 ruby

//小詠
#define		ひとり（ルビ：・・・）			ruby("・・・") ひとり ruby
#define		寛解（かんかい）				ruby("かんかい") 寛解 ruby
#define		洞（うろ）						ruby("うろ") 洞 ruby

//六花
//#replace	義兄							ruby("にい") 義兄ruby
#define		義妹（いもうと）				ruby("いもうと") 義妹 ruby
#define		学校（あそこ）					ruby("あそこ") 学校 ruby
#define		初心（うぶ）					ruby("うぶ") 初心 ruby
#define		人生（たび）					ruby("たび") 人生 ruby
#define		風の回廊（ここ）				ruby("ここ") 風の回廊 ruby
#define		故郷（ふるさと）				ruby("ふるさと") 故郷 ruby
#define		莢（さや）						ruby("さや") 莢 ruby

//スピカzero
#define		風の一族（わたし）				ruby("わたし") 風の一族 ruby

//同棲
#define		畦畔（けいはん）				ruby("けいはん") 畦畔 ruby
#define		側臥位（そくがい）				ruby("そくがい") 側臥位 ruby
#define		生家（せいか）					ruby("せいか") 生家 ruby
#define		性（さが）						ruby("さが") 性 ruby

//クルミ
#define		拙（せつ）						ruby("せつ") 拙 ruby
#define		末節骨（まっせつこつ）			ruby("まっせつこつ") 末節骨 ruby


// 本編中に半角スペース必要なもの
//#define		Ｇ（ご）						ruby("ご") Ｇ ruby
//#define		Ｒ（りっぱ）					ruby("りっぱ") Ｒ ruby
//#define		莢（さや）						ruby("さや") 莢 ruby

// 本編中に一応（）のルビ表示入れたほうがよさそうなもの
#replace	恵庭浩二						ruby("えにわこうじ") 恵庭浩二 ruby


